name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version you want to use

      # Step 3: Change to the backend directory
      - name: Change to backend directory
        run: cd backend

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          cd backend  # Navigate to the backend directory
          npm install

      # Step 5: Start the application
      - name: Start the application
        run: |
          cd backend  # Navigate to the backend directory
          npm start

      # Step 6: Run tests (optional)
      - name: Run tests
        run: |
          cd backend  # Navigate to the backend directory
          npm test
